Addition of Kafka rule
ably/open-specs pull request #20
Opened 2021-11-19 17:04 UTC by tbedford

## Description

Add Kafka rule.

* [DOC-533](https://ably.atlassian.net/browse/DOC-533)

## Checklist for OpenAPI document updates

Please ensure the following:

- [x] Version has been incremented
- [ ] Tested for errors with Spectral
- [ ] Optional: Load into SwaggerHub and check for errors
- [ ] Ensure the document renders under ReDoc (see README for instructions on how to test locally)

## Review

Instructions on how to review the PR.

2021-11-22 17:33 UTC, m-hulbert requested changes
Just a suggestion and one potential rendering issue.

* Version incremented.
* Read through the diff.
* Tested locally - both comments apply to `PATCH` as well.

2021-11-22 17:33 UTC, m-hulbert commented on definitions/control-v1.yaml
> +                      enum:
This doesn't render as expected when running locally (no dropdown). I can't get it to work, so I wonder if it's a Redoc bug?

2021-11-24 10:30 UTC, tbedford commented on definitions/control-v1.yaml
> +              description: Brokers host Kafka partitions. You can provide a list of brokers, using the format `host`, `host:port` or `ip:port`.
Good point. Fixed.

2021-11-24 10:48 UTC, m-hulbert approved these changes

2021-11-24 10:55 UTC, merged