Sources for all rules in single and batch mode
ably/open-specs pull request #21
Opened 2021-11-22 16:33 UTC by tbedford

## Description

The four rule sources are now supported for all rules, in both single and batched mode.

* [DOC-477](https://ably.atlassian.net/browse/DOC-477)

## Checklist for OpenAPI document updates

Please ensure the following:

- [ ] Version has been incremented
- [ ] Tested for errors with Spectral
- [ ] Optional: Load into SwaggerHub and check for errors
- [ ] Ensure the document renders under ReDoc (see README for instructions on how to test locally)

## Review

Instructions on how to review the PR.

2021-11-22 17:04 UTC, tbedford commented
#20 should be merged first.

2021-11-24 18:15 UTC, m-hulbert requested changes
This builds with no problems and the version has been incremented.

My only other suggestion would be that `channel.message` and `channel.presence` read differently to the other two sources - they refer to the events triggering the function calls whereas `channel.lifecycle` and `channel.occupancy` refer to "you receiving notifications..." I'd suggest we standardise on one or the other.

2021-11-24 18:15 UTC, m-hulbert commented on definitions/control-v1.yaml
> +          description: "Ably currently supports the following sources for all rule types, in both single and batch mode: `channel.message`, `channel.presence`, `channel.lifecycle`, `channel.occupancy
```suggestion
          description: "Ably currently supports the following sources for all rule types, in both single and batch mode: `channel.message`, `channel.presence`, `channel.lifecycle` and `channel.occupancy`. If the source `channel.message` is selected, messages trigger function calls as soon as they are published on a channel. If the source `channel.presence` is selected, presence events trigger function calls when clients enter, update their data, or leave channels. If the source `channel.lifecycle` is selected, you receive notifications for channel lifecycle events, such as when a channel is created (following the first client attaching to this channel) or discarded (when there are no more clients attached to the channel). If the source `channel.occupancy` is selected, you receive notifications for occupancy events, which relate to the number and type of occupants in the channel."
```

2021-11-24 18:15 UTC, m-hulbert commented on definitions/control-v1.yaml
> +          description: "Ably currently supports the following sources for all rule types, in both single and batch mode: `channel.message`, `channel.presence`, `channel.lifecycle`, `channel.occupancy
```suggestion
          description: "Ably currently supports the following sources for all rule types, in both single and batch mode: `channel.message`, `channel.presence`, `channel.lifecycle` and `channel.occupancy`. If the source `channel.message` is selected, messages trigger function calls as soon as they are published on a channel. If the source `channel.presence` is selected, presence events trigger function calls when clients enter, update their data, or leave channels. If the source `channel.lifecycle` is selected, you receive notifications for channel lifecycle events, such as when a channel is created (following the first client attaching to this channel) or discarded (when there are no more clients attached to the channel). If the source `channel.occupancy` is selected, you receive notifications for occupancy events, which relate to the number and type of occupants in the channel."
```

2021-11-25 09:01 UTC, m-hulbert approved these changes
LGTM

2021-11-25 09:28 UTC, merged