EDU-1466: Updates the control-v1.yaml with FCM properties
ably/open-specs pull request #39
Opened 2024-01-16 16:35 UTC by franrob-projects

This PR adds the following properties to the control-v1.yaml:

- `fcmServiceAccount`
- `fcmProjectId`

- [x] Version has been incremented
- [x] Tested for errors with Spectral
- [x] Optional: Load into SwaggerHub and check for errors
- [x] Ensure the document renders under ReDoc (see README for instructions on how to test locally)

[EDU-1466: Update control-v1 with FCM properties ](https://ably.atlassian.net/browse/EDU-1466)

2024-01-17 17:33 UTC, GregHolmes approved these changes

2024-01-18 11:32 UTC, m-hulbert requested changes
I think these properties need to be in the PATCH call too, no?

2024-01-22 15:20 UTC, franrob-projects commented
> I think these properties need to be in the PATCH call too, no?

@m-hulbert, please see fixup! 09e8d755972e7ca87f5a48de271ddfcd103e5346

2024-01-24 14:46 UTC, franrob-projects commented on definitions/control-v1.yaml
> +          example: "notional-armor-405018"
Thanks :)

2024-01-24 15:00 UTC, franrob-projects commented on definitions/control-v1.yaml
> +          example: "notional-armor-405018"
@m-hulbert, please see: 3276e0a407d80ea81aadb045e0445a763df9ea58

2024-02-15 10:39 UTC, m-hulbert approved these changes
Rebase and good to go

2024-02-15 20:19 UTC, merged